# Development Environment Configuration
# Financial Data Streaming System

environment: development
debug: true

database:
  mongodb_uri: "mongodb://localhost:27017/stockdata"
  mongodb_database: "stockdata"
  connection_timeout: 30000
  max_pool_size: 50
  retry_writes: true

api:
  alpha_vantage_api_key: "AS0C2O859HMRJXVL"
  alpha_vantage_base_url: "https://www.alphavantage.co/query"
  api_rate_limit: 5
  request_timeout: 30
  max_retries: 3

aws:
  region: "us-east-2"
  sns_topic_arn: "arn:aws:sns:us-east-2:000936194577:financial-data-events"
  use_iam_role: false

kafka:
  bootstrap_servers: "localhost:9092"
  topic: "stock-ticks"
  group_id: "financial-streaming-dev"
  auto_offset_reset: "latest"
  enable_auto_commit: true

accumulo:
  instance_name: "stockdata"
  zookeeper_hosts: "localhost:2181"
  username: "root"
  password: ""
  table_name: "stock_ticks"

service:
  api_server_host: "0.0.0.0"
  api_server_port: 8000
  stream_receiver_host: "0.0.0.0"
  stream_receiver_port: 8002
  driver_host: "0.0.0.0"
  driver_port: 8001
  monitoring_host: "0.0.0.0"
  monitoring_port: 8080

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/app.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5

security:
  enable_ssl: false
  ssl_cert_path: ""
  ssl_key_path: ""
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:8080"
  api_key_required: false
  jwt_secret: "dev-secret-key-change-in-production"

monitoring:
  health_check_interval: 30
  metrics_collection_interval: 60
  alert_check_interval: 60
  response_time_warning: 2.0
  response_time_error: 5.0
  error_rate_warning: 0.05
  error_rate_error: 0.10 